### ISSUE TITLE
G code file with T0 error when loaded on Ormerod firmware 078b

### ISSUE THREAD

**Issue by ingpconci** [Cash70/EAtoR#1]
Slicer: 
Win 7 Cura 14.07 with plugin EAtoR and Cura14.03_presets
Printer:
RepRap Ormerod1 with RepRapFirmware-078b-26-08-2014

With the original File it is no possible to print
....
M109 T0 S205.000000
T0
M190 S55.000000
;Sliced at: Wed 17-09-2014 11:09:43
.......

I've modified the file removing the TO  and the printing is ok
M109 S205.000000
M190 S55.000000
;Sliced at: Wed 17-09-2014 11:09:43

**Comment by Cash70** [comment]
Thank you!
